web:
  build: .
  ports: 
    - "8080:8080"
    - "8085:8085"
    - "5858:5858"
  links:
    - dynamodb
    - s3
  environment:
    - DYNAMODB_HOST=dynamodb
    - S3_HOST=s3
  volumes:
    - '.:/usr/src/app'
dynamodb:
  image: instructure/dynamodb:latest
s3:
  image: lphoward/fake-s3:latest
  ports: 
    - "4569:4569"
