webapp:
  build: ./angularApp
  ports: 
    - "9000:9000"
  volumes:
   - './angularApp/:/usr/src/app'
   - /usr/src/app/node_modules
server:
  build: ./server/
  ports: 
    - "8080:8080"
    - "8085:8085"
    - "5858:5858"
  links:
    - dynamodb
    - s3
  environment:
    - DYNAMODB_HOST=dynamodb
    - S3_HOST=s3
  volumes:
    - './server/:/usr/src/app'
    - /usr/src/app/node_modules
dynamodb:
  image: instructure/dynamodb:latest
  ports:
    - "8000:8000"
s3:
  image: lphoward/fake-s3:latest
  ports: 
    - "4569:4569"
